/* generated by Svelte v3.59.2 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "svelte/internal";

function create_fragment(ctx) {
	let header0;
	let t0;
	let header1;
	let current;
	header0 = new Header({});

	return {
		c() {
			create_component(header0.$$.fragment);
			t0 = space();
			header1 = element("header");
			header1.textContent = "I am header";
		},
		m(target, anchor) {
			mount_component(header0, target, anchor);
			insert(target, t0, anchor);
			insert(target, header1, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(header0.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(header0.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(header0, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(header1);
		}
	};
}

let x = 1;

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default App;